### ISSUE TITLE
Typo in line 123

### ISSUE THREAD

**Issue by zenny** [tslenter/Remote_Syslog#1]
Hi Tom ,

Your script is fabulous for what it was meant for. Thanks @tslenter.

However, there seems to be a typo in line 123 in https://github.com/tslenter/Remote_Syslog/blob/master/rsinstaller.c , I guess.

> printf("Notice: This installation is tested for Debian 8.9 or higher...\n");

should be:

> printf("Notice: This installation is tested for Debian 8.7 or higher...\n");

Cheers,
/z

**Comment by tslenter** [comment]
Hi,

Happy to hear that the script worked fine. I saw the improvement and you're correct. I will add the improvement in the next release.

Thanks for notifying me.
